version: "3.9"

services:
  socks_db:
    container_name: socks_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata: {}

networks:
  my_network:
    